name: CI Checks & Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "CI Build"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM Install
        run: npm install --silent

      - name: Lint Check
        run: npm run lint

      - name: Bundle
        run: npm run build